docType = "{{.NameCamelCase }}"
tableComment = "{{.NameRu}}"

tableName ="{{.Name }}"

{{.PrintSqlModelFlds}}

{{$.PrintSqlModelFkConstraints}}

{{.PrintSqlModelTriggers}}

{{.PrintSqlModelIndexes}}

{{.PrintSqlModelMethods}}

{{.PrintSqlModelAlterScripts}}