docType = "{{.Name | UpperCaseFirst}}"
tableComment = "{{.NameRu}}"

tableName ="{{.Name | ToLowerCamel}}"

{{.PrintSqlModelFlds}}

{{$.PrintSqlModelFkConstraints}}

{{.PrintSqlModelTriggers}}

{{.PrintSqlModelMethods}}