
[postgres]
user = "postgres"
password = "{{.Config.Postgres.Password}}"
dbName = "{{.Config.Postgres.DbName}}"
host = "postgres"
port = 5432
modelDir = ["./sql/model"]
viewDir = ["./sql/view"]
templateDir = ["./sql/template"]

[webServer]
enable = true
port = {{.Config.WebServer.Port}}
url = "{{.Config.WebServer.Url}}"

{{ if .Config.Graylog.Host -}}
[graylog]
host = "{{.Config.Graylog.Host}}"
port = {{.Config.Graylog.Port}}
{{- end}}

[email]
sender = "{{.Config.Email.Sender}}"
password = "{{.Config.Email.Password}}"
host = "{{.Config.Email.Host}}"
port = {{.Config.Email.Port}}
senderName = "{{.Config.Email.SenderName}}"
isSendWithEmptySender = {{.Config.Email.IsSendWithEmptySender}}

{{if .IsTelegramIntegration -}}
[telegram]
botName = "{{.Config.Telegram.BotName}}"
token = "{{.Config.Telegram.Token}}"
{{- end}}

{{if .IsBitrixIntegration -}}
[bitrix]
apiUrl = "{{.Config.Bitrix.ApiUrl}}"
userId = "{{.Config.Bitrix.UserId}}"
webhookToken = "{{.Config.Bitrix.WebhookToken}}"
{{- end}}

{{if .IsOdataIntegration -}}
[odata]
url = "{{.Config.Odata.Url}}"
login = "{{.Config.Odata.Login}}"
password = "{{.Config.Odata.Password}}"
exchangePlanName = "{{.Config.Odata.ExchangePlanName}}"
exchangePlanGuid = "{{.Config.Odata.ExchangePlanGuid}}"
{{- end}}


