
[postgres]
user = "postgres"
password = "{{.Config.Postgres.Password}}"
dbName = "{{.Config.Postgres.DbName}}"
host = "postgres"
port = 5432
modelDir = ["./sql/model"]
viewDir = ["./sql/view"]
templateDir = ["./sql/template"]

[webServer]
enable = true
port = {{.Config.WebServer.Port}}
url = "{{.Config.WebServer.Url}}"

[graylog]
host = "85.143.214.161"
port = 12201

[email]
sender = "{{.Config.Email.Sender}}"
password = "{{.Config.Email.Password}}"
host = "{{.Config.Email.Host}}"
port = {{.Config.Email.Port}}
senderName = "{{.Config.Email.SenderName}}"

{{if .IsTelegramIntegration -}}
[telegram]
botName = "{{.Config.Telegram.BotName}}"
token = "{{.Config.Telegram.Token}}"
{{- end}}

{{if .IsBitrixIntegration -}}
[bitrix]
apiUrl = "{{.Config.Bitrix.ApiUrl}}"
userId = "{{.Config.Bitrix.UserId}}"
webhookToken = "{{.Config.Bitrix.WebhookToken}}"
{{- end}}



