{{$projectNameSnake := .Config.Postgres.DbName -}}
{{$serverPath := .Config.WebServer.Path -}}
{{$webPort := .Config.WebServer.Port -}}
{{$volumes := .Config.Docker.Volumes -}}
version: '2'
services:
  bot:
    build: .
    cpu_shares: 73
    networks:
      - {{$projectNameSnake}}_net
    volumes:
      - {{$serverPath}}/src/config.toml:/config.toml
      - {{$serverPath}}/image:/image
      - {{$serverPath}}/uploaded_files:/uploaded_files
      {{- range $volumes}}
      - {{.}}
      {{- end}}
    ports:
      - "{{$webPort}}:{{$webPort}}"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://85.143.214.161:12201"
        tag: docker.app.{{$projectNameSnake}}
    depends_on:
      - postgres

  postgres:
    image: postgres:{{.Config.Postgres.Version}}
    networks:
      - {{$projectNameSnake}}_net
    volumes:
      - {{$serverPath}}/postgres/volume:/var/lib/postgresql/data
      - {{$serverPath}}/postgres/logs:/logs
    ports:
      - "{{.Config.Postgres.Port}}:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_PASSWORD: {{.Config.Postgres.Password}}

networks:
  {{$projectNameSnake}}_net:
    driver: bridge